### ISSUE TITLE
Mysql Class not found exeption

### ISSUE THREAD

**Issue by ArmaniS-Dev** [yawek9/discordverifier#1]
[10:16:57] [Velocity Async Event Executor - #0/INFO]: discordverifier-hikari - Starting...
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: Couldn't connect to MySQL database.
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.MysqlDataSource
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:106)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:322)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:112)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:93)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at xyz.yawek9.discordverifier.data.MySQLDataAccess.openDatabaseConnection(MySQLDataAccess.java:24)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at xyz.yawek9.discordverifier.VelocityDiscordVerifier.onInitialize(VelocityDiscordVerifier.java:45)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at xyz.yawek9.discordverifier.Lmbda$5.execute(Unknown Source)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.MysqlDataSource
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:93)
[10:16:57] [Velocity Async Event Executor - #0/ERROR]: 	... 13 more
[10:16:58] [Velocity Async Event Executor - #0/INFO]: Login Successful!
[10:16:58] [JDA MainWS-ReadThread/INFO]: Connected to WebSocket
[10:16:58] [JDA MainWS-WriteThread/ERROR]: WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode(4014 / Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES or GUILD_MEMBERS.)
[10:16:58] [Velocity Async Event Executor - #0/ERROR]: Couldn't pass ProxyInitializeEvent to discordverifier
java.lang.IllegalStateException: Was shutdown trying to await status
	at net.dv8tion.jda.internal.JDAImpl.awaitStatus(JDAImpl.java:482) ~[?:?]
	at net.dv8tion.jda.api.JDA.awaitStatus(JDA.java:315) ~[?:?]
	at net.dv8tion.jda.api.JDA.awaitReady(JDA.java:365) ~[?:?]

An unknown plugin has shaded the library 'HikariCP' but did not relocate it. This may or may not pose problems. Contact the author of this plugin and tell them to relocate their dependencies. Unrelocated class detected was com.zaxxer.hikari.HikariConfig

**Comment by yawek9** [comment]
Fixed. I can also see in your logs that you didn't enabled Discord bot server members intents. You have to enable it, otherwise the bot will not work.
![image](https://user-images.githubusercontent.com/82580456/150383105-c23eca1f-06d6-4a00-8058-bf361dd8e78f.png)
